### PR TITLE
Fix bugs 1160214 and 1170709 - Support unnumbered future versions, {{CompatNightly}}

### PR DESCRIPTION
**Pull request by jwhitlock**
*This PR builds on previous PRs, and can be rebased when those are merged*

Restrict the valid combinations of Version.version and .status:

* version can not be blank
* version is write-once, and cannot be updated
* For status "current", version is "current" or numeric
* For status "beta", "retired beta", "retired", and "unknown", version must be numeric
* For status "future", version must be text

The scraper has been updated to:
* Convert the "unknown version" (such as `{{CompatNo}}`) to version="current", status="current"
* Convert `{{CompatNightly}}` to version="nightly", status="future"

https://browsercompat.herokuapp.com has been updated with the new code and migrations, but the scraper has not been rerun against all pages.

### CODE REVIEW

**Comment by jwhitlock** [comment]
The "unknown" version changed from version=null, status="unknown" to version="current", status="current".  The MDN importer needs to be updated with the new pattern.  This can be done with the fix to [bug 1170709](https://bugzilla.mozilla.org/show_bug.cgi?id=1170709) to support mapping `{{CompatNightly}}` to version="nightly", status="future".

**Comment by jwhitlock** [comment]
Added two commits to update the scraper for the new API code.

**Comment by jezdez** [comment]
LGTM rwc+ (notwithstanding comments made in the previous PRs)

**Comment by jwhitlock** [comment]
Dropped unneeded ``blank=False``.

**Pull request merged**
