### PR TITLE
Fix bug 1146430 - Update to DRF 3.1

### PR DESCRIPTION
**Pull request by jwhitlock**
This code upgrades Django REST Framework (DRF) from 2.4 to 3.1, with as little changes to tests as possible.  It is done as a series of 2.4-compatible changes, followed by a final commit with the 2.4 to 3.1 changes.  It will probably be easier to review by commit rather than by branch diff, except for the final commit, which is difficult no matter what you do. 

Based on the upgrade experience, using DRF's `ModelSerializer` with our complex models and rendering with [drf-json-api](https://github.com/kevin-brown/drf-json-api) require overriding methods in ways that make little sense.  Re-implenting the serializers and renderer is planned in [bug 1153288](https://bugzilla.mozilla.org/show_bug.cgi?id=1153288).

Despite the ugliness, it's a good idea to get off of DRF 2.4, which the DRF maintainers are slow to update, even for security fixes.

### CODE REVIEW

**Comment by jwhitlock** [comment]
I found some API issues using `tools/upload_data.py`, updated the "Update to DRF 3.1" commit, and added a second one:

- In `OptionalCharField`, handle validation of None for empty fields
- Add a default of an empty list for to-many related fields
- JSON now includes Unicode instead of unicode-escaped ASCII, modified deserializing JSON

**Comment by jwhitlock** [comment]
And another fix, to use delayed cache invalidation for DELETEs as well as POST and PUT.

**Comment by jwhitlock** [comment]
And a test of DELETE in changeset for code coverage.

**Comment by groovecoder** [comment]
No blockers. Some comments that could turn into future tasks or bugs, but I'll go ahead an merge this after I do a local spot-check.

**Comment by groovecoder** [comment]
Spot checks look good. I was able to reload data with command-line tools, browse the data, explore the API, and re-import data with the MDN importer.

**Comment by jwhitlock** [comment]
:smile_cat:

**Pull request merged**
