### PR TITLE
fix bug 1139111 - Add requires.io support

### PR DESCRIPTION
**Pull request by jwhitlock**
Add requires.io badge, and updates requirements.txt and requirements-dev.txt (see [before](https://requires.io/github/jwhitlock/web-platform-compat/requirements/?branch=master) and [after](https://requires.io/github/jwhitlock/web-platform-compat/requirements/?branch=1139111_requires)).  Fixes [Bugzilla 1139111](https://bugzilla.mozilla.org/show_bug.cgi?id=1139111).  Builds on PR #21, can rebase when merged.

### CODE REVIEW

**Comment by jwhitlock** [comment]
PR #21 has some significant changes.  Planning to rebase and refresh requirements when that is accepted.

**Comment by jwhitlock** [comment]
Rebased, requirements refreshed, green as of now: https://requires.io/github/jwhitlock/web-platform-compat/requirements/?branch=1139111_requires

**Comment by groovecoder** [comment]
Merged #21. Should this get another rebase?

**Comment by jwhitlock** [comment]
Rebased on new master, still [green](https://requires.io/github/jwhitlock/web-platform-compat/requirements/?branch=1139111_requires).

**Pull request merged**
